services:  
  postgres:
     image: postgres:14-alpine
     container_name: postgres
     volumes:
       - /tmp/postgres:/var/lib/postgresql/data
       - ./scripts/:/docker-entrypoint-initdb.d/
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=Postgres2018!
       - POSTGRES_DB=bd1
     networks:
       - open-network
     ports:
       - "5432:5432"
networks:
  open-network:
    driver: bridge

